name: tipster
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  firebase_auth: ^4.17.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  form_validator: ^2.1.1
  get_it: ^7.6.7
  iconsax: ^0.0.8
  shared_preferences: ^2.2.2
  # auto_route: ^7.8.4
  # flutter_screenutil: ^5.9.0
  # flutter_bloc: ^8.1.4
  # iconsax: ^0.0.8
  # firebase_auth: ^4.17.6
  # firebase_core: ^2.25.5
  # shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2


flutter:
  uses-material-design: true
