// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfAwTZDKLe6gO92cHN4kzOdGpV8gx4ElE',
    appId: '1:482854317068:web:ef3cadfffef19fd767d229',
    messagingSenderId: '482854317068',
    projectId: 'tipster-f568e',
    authDomain: 'tipster-f568e.firebaseapp.com',
    storageBucket: 'tipster-f568e.appspot.com',
    measurementId: 'G-M5LVC39FDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBydEc-uuWE80E9MC7Tj8Ns1TuV_kjqeAo',
    appId: '1:482854317068:android:573f1477fc9bd0d067d229',
    messagingSenderId: '482854317068',
    projectId: 'tipster-f568e',
    storageBucket: 'tipster-f568e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFAhrWkJf3CKMqfBGiz6my1ohTDcPb24w',
    appId: '1:482854317068:ios:6d1ff172ebeced4367d229',
    messagingSenderId: '482854317068',
    projectId: 'tipster-f568e',
    storageBucket: 'tipster-f568e.appspot.com',
    iosBundleId: 'com.example.tipster',
  );
}
